# 2024-05-21 03:07

FIRST_SET = {
    "<program>": "seed",
    "<global>": ["floral", "EPSILON"],
    "<constant>": ["hard", "EPSILON"],
    "<statement>": [
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "mint",
        "leaf",
        "fern",
        "willow",
        "tree",
        "clear",
        "break",
        "EPSILON",
    ],
    "<insert-variable>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<common-type>": ["tint", "flora", "chard", "string", "bloom"],
    "<common-data>": ["=", "EPSILON"],
    "<insert-data>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "(",
    ],
    "<insert-operation>": [
        "tint literal",
        "lent",
        "tint",
        "#",
        "flora literal",
        "flora",
        "chard literal",
        "string literal",
        "bloom literal",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<data>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "EPSILON",
    ],
    "<open-parenthesis>": ["(", "EPSILON"],
    "<close-parenthesis>": [")", "EPSILON"],
    "<arithmetic>": ["tint literal", "lent", "tint", "#", "flora literal", "flora"],
    "<operate-number>": ["+", "-", "*", "/", "%", "**", "//", "EPSILON"],
    "<operator>": ["+", "-", "*", "/", "%", "**", "//"],
    "<tint>": ["tint literal", "lent", "tint", "#"],
    "<flora>": ["flora literal", "flora", "#"],
    "<concatenate>": ["[", "+", "EPSILON"],
    "<condition>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<operate-logic>": [
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "EPSILON",
    ],
    "<cond-operator>": ["==", "!=", ">", "<", ">=", "<=", "=&", "=/", "at", "nut"],
    "<nuts-and-ats>": ["at", "nut", "EPSILON"],
    "<supply-dirt>": ["getItems", "getKeys", "getValues"],
    "<insert-func>": ["(", "EPSILON"],
    "<instance-grab>": [",", "EPSILON"],
    "<indexing>": ["[", "EPSILON"],
    "<insert-index>": ["string literal", "tint literal"],
    "<typecast>": ["(", "EPSILON"],
    "<more-data>": [",", "EPSILON"],
    "<sqnc-type>": ["florist", "tulip", "dirt", "stem"],
    "<sqnc-value>": ["=", "EPSILON"],
    "<sequence>": [
        "string literal",
        "[",
        "{",
        "getItems",
        "getKeys",
        "getValues",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
    ],
    "<open>": ["[", "{"],
    "<dirt>": ["string literal", "EPSILON"],
    "<close>": ["]", "}"],
    "<more-sqnc>": [",", "EPSILON"],
    "<insert-sqnc>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "*",
        "EPSILON",
    ],
    "<next-sqnc>": [",", "EPSILON"],
    "<insert-next-sqnc>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "EPSILON",
        "*",
    ],
    "<start-end-step>": ["[", "EPSILON"],
    "<insert-start>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "(",
        ":",
    ],
    "<close-start>": [
        "]",
        ":",
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "(",
    ],
    "<close-end>": ["]", ":"],
    "<skip-start>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "(",
        ":",
    ],
    "<all-type-value>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
    ],
    "<i/o-statement>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "mint",
    ],
    "<insert-inpetal>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
    ],
    "<inpetal-state>": ["string literal", "EPSILON"],
    "<more-id>": [",", "EPSILON"],
    "<eleaf>": ["eleaf", "EPSILON"],
    "<else>": ["moss", "EPSILON"],
    "<assignment>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
    ],
    "<assign>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "EPSILON",
    ],
    "<insert-assign>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<assignment-op>": ["=", "+=", "-=", "*=", "/=", "%=", "**=", "//="],
    "<iterative>": ["fern", "willow"],
    "<insert-fern>": [
        "tint",
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
    ],
    "<more-value>": [",", "EPSILON"],
    "<check-branch>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
        "_",
    ],
    "<insert-branch>": [":", "leaf"],
    "<operate-branch>": [
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "mint",
        "leaf",
        "fern",
        "willow",
        "tree",
        "clear",
        "break",
        "EPSILON",
        "_:",
    ],
    "<more-branch>": ["branch", "EPSILON"],
    "<argument>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
        "EPSILON",
    ],
    "<insert-argument>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
        "EPSILON",
    ],
    "<add-argument>": [",", "EPSILON"],
    "<more**kwargs>": [",", "EPSILON"],
    "<function>": ["tint", "flora", "chard", "string", "bloom", "viola", "EPSILON"],
    "<add-at>": [",", "at", "EPSILON"],
    "<parameter>": [
        "tint",
        "flora",
        "string",
        "bloom",
        "**",
        "EPSILON",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
    ],
    "<undefined-param>": ["tint", "flora", "chard", "string", "bloom", "**", "#", "EPSILON"],
    "<add-kwargs>": [",", "EPSILON"],
    "<next-parameter>": [",", "EPSILON"],
}


FOLLOW_SET = {
    "<program>": "EPSILON",
    "<global>": "garden",
    "<constant>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<statement>": [")", "regrow"],
    "<insert-variable>": ";",
    "<common-type>": ["#", "(", "EPSILON", "*"],
    "<common-data>": [",", "EPSILON", ";", ")"],
    "<insert-data>": [",", "EPSILON", ";", ")"],
    "<insert-operation>": [",", "EPSILON", ";", ")"],
    "<data>": [
        ",",
        "EPSILON",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "]",
        "}",
    ],
    "<open-parenthesis>": [
        "tint literal",
        "lent",
        "tint",
        "#",
        "flora literal",
        "flora",
        "chard literal",
        "string literal",
        "bloom literal",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<close-parenthesis>": [
        ",",
        "EPSILON",
        ";",
        ")",
        "+",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
    ],
    "<arithmetic>": [")", "EPSILON", ",", ";"],
    "<operate-number>": [")", "EPSILON", ",", ";"],
    "<operator>": ["(", "tint literal", "lent", "tint", "#", "flora literal", "flora"],
    "<tint>": ["+", "-", "*", "/", "%", "**", "//", "EPSILON", ")", ",", ";"],
    "<flora>": ["+", "-", "*", "/", "%", "**", "//", "EPSILON", ")", ",", ";"],
    "<concatenate>": [
        "+",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "EPSILON",
        ",",
        ";",
        ")",
    ],
    "<condition>": [")", "EPSILON", ",", ";"],
    "<operate-logic>": [")", "EPSILON", ",", ";"],
    "<cond-operator>": [
        "(",
        "EPSILON",
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<nuts-and-ats>": [
        "(",
        "EPSILON",
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<supply-dirt>": "(",
    "<insert-func>": [
        "[",
        "EPSILON",
        ",",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "+",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        ",",
        ";",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
    ],
    "<instance-grab>": [
        "[",
        "EPSILON",
        ",",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "+",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        ",",
        ";",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
    ],
    "<indexing>": [
        "[",
        "EPSILON",
        ",",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "+",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        ",",
        ";",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
    ],
    "<typecast>": [
        ",",
        "EPSILON",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
    ],
    "<more-data>": ";",
    "<sqnc-type>": ["#", "("],
    "<sqnc-value>": [",", "EPSILON", ";"],
    "<sequence>": [
        "==",
        "!=",
        ">",
        "<",
        ">=," "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "EPSILON",
        ")",
        ",",
        ";",
        "at",
    ],
    "<open>": [
        "string literal",
        "tint literal",
        "flora literal",
        "chard literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
    ],
    "<dirt>": [
        "[",
        "{",
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal" "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "]",
        "}",
    ],
    "<close>": [
        "==",
        "!=",
        ">",
        "<",
        ">=," "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "EPSILON",
        ",",
        "]",
        "}",
    ],
    "<more-sqnc>": ";",
    "<insert-sqnc>": ["]", "}"],
    "<next-sqnc>": ["]", "}"],
    "<insert-next-sqnc>": ["]", "}"],
    "<start-end-step>": [
        "[",
        "+",
        "EPSILON",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        ",",
        ";",
        ")",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
    ],
    "<insert-start>": [
        "[",
        "+",
        "EPSILON",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        ",",
        ";",
        ")",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
    ],
    "<close-start>": [
        "[",
        "+",
        "EPSILON",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        ",",
        ";",
        ")",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
    ],
    "<close-end>": [
        "[",
        "+",
        "EPSILON",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        ",",
        ";",
        ")",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
    ],
    "<skip-start>": [
        "[",
        "+",
        "EPSILON",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        ",",
        ";",
        ")",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
    ],
    "<all-type-value>": [
        "[" ")",
        "+",
        "EPSILON",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut" ";",
        ",",
        "at",
        ":",
        "leaf",
    ],
    "<i/o-statement>": ";",
    "<insert-inpetal>": "inpetal",
    "<inpetal-state>": ")",
    "<more-id>": ["=", "+=", "-=", "*=", "/=", "%=", "**=", "//="],
    "<eleaf>": [
        "moss",
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "mint",
        "leaf",
        "fern",
        "willow",
        "tree",
        "clear",
        "break",
        "EPSILON",
        ")",
        "regrow",
    ],
    "<else>": [
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "mint",
        "leaf",
        "fern",
        "willow",
        "tree",
        "clear",
        "break",
        "EPSILON",
        ")",
        "regrow",
    ],
    "<assignment>": ";",
    "<assign>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<insert-assign>": [",", "EPSILON", ";"],
    "<assignment-op>": ["inpetal", "tint literal", "lent", "tint", "#"],
    "<iterative>": ";",
    "<insert-fern>": ";",
    "<more-value>": [";", "at"],
    "<check-branch>": ")",
    "<insert-branch>": ["branch", ")", "EPSILON"],
    "<operate-branch>": ["branch", ")", "EPSILON"],
    "<more-branch>": ")",
    "<argument>": ")",
    "<insert-argument>": ")",
    "<add-argument>": ")",
    "<more**kwargs>": ")",
    "<function>": "plant",
    "<add-at>": ";",
    "<parameter>": ")",
    "<undefined-param>": ")",
    "<add-kwargs>": ")",
    "<next-parameter>": ")",
}
