# 2024-05-16 02:14

FIRST_SET = {
    "<program>": "seed",
    "<global>": ["floral", "EPSILON"],
    "<constant>": ["hard", "EPSILON"],
    "<statement>": [
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "mint",
        "leaf",
        "fern",
        "willow",
        "tree",
        "clear",
        "break",
        "EPSILON",
    ],
    "<insert-variable>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<common-type>": ["tint", "flora", "chard", "string", "bloom"],
    "<common-data>": ["=", "EPSILON"],
    "<insert-data>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "(",
    ],
    "<insert-operation>": [
        "tint literal",
        "lent",
        "tint",
        "#",
        "flora literal",
        "flora",
        "chard literal",
        "string literal",
        "bloom literal",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<data>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
    ],
    "<open-parenthesis>": ["(", "EPSILON"],
    "<close-parenthesis>": [")", "EPSILON"],
    "<arithmetic>": ["tint literal", "lent", "tint", "#", "flora literal", "flora"],
    "<operate-number>": ["+", "-", "*", "/", "%", "**", "//", "EPSILON"],
    "<operator>": ["+", "-", "*", "/", "%", "**", "//"],
    "<tint>": ["tint literal", "lent", "tint", "#"],
    "<flora>": ["flora literal", "flora", "#"],
    "<concatenate>": ["[", "+", "EPSILON"],
    "<condition>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<operate-logic>": [
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "EPSILON",
    ],
    "<cond-operator>": ["==", "!=", ">", "<", ">=", "<=", "=&", "=/", "at", "nut"],
    "<nuts-and-ats>": ["at", "nut", "EPSILON"],
    "<supply-dirt>": ["getItems", "getKeys", "getValues"],
    "<insert-func>": ["(", "EPSILON"],
    "<instance-grab>": [",", "EPSILON"],
    "<indexing>": ["[", "EPSILON"],
    "<typecast>": ["(", "EPSILON"],
    "<more-data>": [",", "EPSILON"],
    "<sqnc-type>": ["florist", "tulip", "dirt", "stem"],
    "<sqnc-value>": ["=", "EPSILON"],
    "<sequence>": [
        "string literal",
        "[",
        "{",
        "getItems",
        "getKeys",
        "getValues",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
    ],
    "<open>": ["[", "{"],
    "<dirt>": ["string literal", "EPSILON"],
    "<close>": ["]", "}"],
    "<more-sqnc>": [",", "EPSILON"],
    "<insert-sqnc>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "*",
        "EPSILON",
    ],
    "<next-sqnc>": [",", "EPSILON"],
    "<insert-next-sqnc>": ["string literal", "EPSILON", "*"],
    "<start-end-step>": ["[", "EPSILON"],
    "<insert-start>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "(",
        ":",
    ],
    "<close-start>": [
        "]",
        ":",
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "(",
    ],
    "<close-end>": ["]", ":"],
    "<skip-start>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "(",
        ":",
    ],
    "<all-type-value>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
    ],
    "<i/o-statement>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "mint",
    ],
    "<insert-inpetal>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
    ],
    "<more-id>": [",", "EPSILON"],
    "<eleaf>": ["eleaf", "EPSILON"],
    "<else>": ["moss", "EPSILON"],
    "<assignment>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
    ],
    "<assign>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "EPSILON",
    ],
    "<insert-assign>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<assignment-op>": ["=", "+=", "-=", "*=", "/=", "%=", "**=", "//="],
    "<iterative>": ["fern", "willow"],
    "<insert-fern>": [
        "tint",
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
    ],
    "<more-value>": [",", "EPSILON"],
    "<check-branch>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
        "_:",
    ],
    "<insert-branch>": [":", "leaf"],
    "<operate-branch>": [
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "mint",
        "leaf",
        "fern",
        "willow",
        "tree",
        "clear",
        "break",
        "EPSILON",
        "_:",
    ],
    "<more-branch>": ["branch", "EPSILON"],
    "<argument>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
        "EPSILON",
    ],
    "<insert-argument>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
        "EPSILON",
    ],
    "<add-argument>": [",", "EPSILON"],
    "<more**kwargs>": [",", "EPSILON"],
    "<function>": ["tint", "flora", "chard", "string", "bloom", "viola", "EPSILON"],
    "<add-at>": [",", "at", "EPSILON"],
    "<parameter>": [
        "tint",
        "flora",
        "string",
        "bloom",
        "**",
        "EPSILON",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
    ],
    "<undefined-param>": ["tint", "flora", "chard", "string", "bloom", "**", "EPSILON"],
    "<add-kwargs>": [",", "EPSILON"],
    "<next-parameter>": [",", "EPSILON"],
}


FOLLOW_SET = {
    "<program>": "EPSILON",
    "<global>": "garden",
    "<constant>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<statement>": [")", "regrow"],
    "<insert-variable>": ";",
    "<common-type>": ["#", "(", "EPSILON", "*"],
    "<common-data>": [",", "EPSILON", ";", ")"],
    "<insert-data>": [",", "EPSILON", ";", ")"],
    "<insert-operation>": [",", "EPSILON", ";", ")"],
    "<data>": [
        ",",
        "EPSILON",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "]",
        "}",
    ],
    "<open-parenthesis>": [
        "tint literal",
        "lent",
        "tint",
        "#",
        "flora literal",
        "flora",
        "chard literal",
        "string literal",
        "bloom literal",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<close-parenthesis>": [
        ",",
        "EPSILON",
        ";",
        ")",
        "+",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
    ],
    "<arithmetic>": [")", "EPSILON", ",", ";"],
    "<operate-number>": [")", "EPSILON", ",", ";"],
    "<operator>": ["(", "tint literal", "lent", "tint", "#", "flora literal", "flora"],
    "<tint>": ["+", "-", "*", "/", "%", "**", "//", "EPSILON", ")", ",", ";"],
    "<flora>": ["+", "-", "*", "/", "%", "**", "//", "EPSILON", ")", ",", ";"],
    "<concatenate>": [
        "+",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "EPSILON",
        ",",
        ";",
        ")",
    ],
    "<condition>": [")", "EPSILON", ",", ";"],
    "<operate-logic>": [")", "EPSILON", ",", ";"],
    "<cond-operator>": [
        "(",
        "EPSILON",
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<nuts-and-ats>": [
        "(",
        "EPSILON",
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<supply-dirt>": "(",
    "<insert-func>": [
        "[",
        "EPSILON",
        ",",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "+",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        ",",
        ";",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
    ],
    "<instance-grab>": [
        "[",
        "EPSILON",
        ",",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "+",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        ",",
        ";",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
    ],
    "<indexing>": [
        "[",
        "EPSILON",
        ",",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "+",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        ",",
        ";",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
    ],
    "<typecast>": [
        ",",
        "EPSILON",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
    ],
    "<more-data>": ";",
    "<sqnc-type>": ["#", "("],
    "<sqnc-value>": [",", "EPSILON", ";"],
    "<sequence>": [
        "==",
        "!=",
        ">",
        "<",
        ">=," "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "EPSILON",
        ")",
        ",",
        ";",
        "at",
    ],
    "<open>": [
        "string literal",
        "tint literal",
        "flora literal",
        "chard literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
    ],
    "<dirt>": [
        "[",
        "{",
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal" "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "]",
        "}",
    ],
    "<close>": [
        "==",
        "!=",
        ">",
        "<",
        ">=," "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "EPSILON",
        ",",
        "]",
        "}",
    ],
    "<more-sqnc>": ";",
    "<insert-sqnc>": ["]", "}"],
    "<next-sqnc>": ["]", "}"],
    "<insert-next-sqnc>": ["]", "}"],
    "<start-end-step>": [
        "[",
        "+",
        "EPSILON",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        ",",
        ";",
        ")",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
    ],
    "<insert-start>": [
        "[",
        "+",
        "EPSILON",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        ",",
        ";",
        ")",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
    ],
    "<close-start>": [
        "[",
        "+",
        "EPSILON",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        ",",
        ";",
        ")",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
    ],
    "<close-end>": [
        "[",
        "+",
        "EPSILON",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        ",",
        ";",
        ")",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
    ],
    "<skip-start>": [
        "[",
        "+",
        "EPSILON",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        ",",
        ";",
        ")",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
    ],
    "<all-type-value>": [
        "[" ")",
        "+",
        "EPSILON",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut" ";",
        ",",
        "at",
        ":",
        "leaf",
    ],
    "<i/o-statement>": ";",
    "<insert-inpetal>": "inpetal",
    "<more-id>": ["=", "+=", "-=", "*=", "/=", "%=", "**=", "//="],
    "<eleaf>": [
        "moss",
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "mint",
        "leaf",
        "fern",
        "willow",
        "tree",
        "clear",
        "break",
        "EPSILON",
        ")",
        "regrow",
    ],
    "<else>": [
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "mint",
        "leaf",
        "fern",
        "willow",
        "tree",
        "clear",
        "break",
        "EPSILON",
        ")",
        "regrow",
    ],
    "<assignment>": ";",
    "<assign>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<insert-assign>": [",", "EPSILON", ";"],
    "<assignment-op>": ["inpetal", "tint literal", "lent", "tint", "#"],
    "<iterative>": ";",
    "<insert-fern>": ";",
    "<more-value>": [";", "at"],
    "<check-branch>": ")",
    "<insert-branch>": ["branch", ")", "EPSILON"],
    "<operate-branch>": ["branch", ")", "EPSILON"],
    "<more-branch>": ")",
    "<argument>": ")",
    "<insert-argument>": ")",
    "<add-argument>": ")",
    "<more**kwargs>": ")",
    "<function>": "plant",
    "<add-at>": ";",
    "<parameter>": ")",
    "<undefined-param>": ")",
    "<add-kwargs>": ")",
    "<next-parameter>": ")",
}

PREDICT_SET = {
    "<program>_seed": "seed",
    "<global>_floral": "floral",
    "<global>_EPSILON": "garden",
    "<constant>_hard": "hard",
    "<constant>_EPSILON": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<statement>_<constant>": ["hard", "EPSILON"],
    "<statement>_<i/o-statement>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "mint",
    ],
    "<statement>_leaf": "leaf",
    "<statement>_<assignment>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
    ],
    "<statement>_<iterative>": ["fern", "willow"],
    "<statement>_tree": "tree",
    "<statement>_clear": "clear",
    "<statement>_break": "break",
    "<statement>_EPSILON": [")", "regrow"],
    "<insert-variable>_<common-type>": ["tint", "flora", "chard", "string", "bloom"],
    "<insert-variable>_<sqnc-type>": ["florist", "tulip", "dirt", "stem"],
    "<common-type>_tint": "tint",
    "<common-type>_flora": "flora",
    "<common-type>_chard": "chard",
    "<common-type>_string": "string",
    "<common-type>_bloom": "bloom",
    "<common-data>_=": "=",
    "<common-data>_EPSILON": [",", "EPSILON", ";", ")"],
    "<insert-data>_<data>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
    ],
    "<insert-data>_<open-parenthesis>": ["(", "EPSILON"],
    "<insert-operation>_<arithmetic>": [
        "tint literal",
        "lent",
        "tint",
        "#",
        "flora literal",
        "flora",
    ],
    "<insert-operation>_<condition>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<data>_tint literal": "tint literal",
    "<data>_flora literal": "flora literal",
    "<data>_chard literal": "chard literal",
    "<data>_string literal": "string literal",
    "<data>_bloom literal": "bloom literal",
    "<data>_#": "#",
    "<data>_lent": "lent",
    "<data>_<common-type>": ["tint", "flora", "chard", "string", "bloom"],
    "<data>_<supply-dirt>": ["getItems", "getKeys", "getValues"],
    "<data>_bare": "bare",
    "<open-parenthesis>_(": "(",
    "<open-parenthesis>_EPSILON": [
        "tint literal",
        "lent",
        "tint",
        "#",
        "flora literal",
        "flora",
        "chard literal",
        "string literal",
        "bloom literal",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<close-parenthesis>_)": ")",
    "<close-parenthesis>_EPSILON": [",", "EPSILON", ";", ")"],
    "<arithmetic>_<tint>": ["tint literal", "lent", "tint", "#"],
    "<arithmetic>_<flora>": ["flora literal", "flora", "#"],
    "<operate-number>_<operator>": ["+", "-", "*", "/", "%", "**", "//"],
    "<operate-number>_EPSILON": [")", "EPSILON", ",", ";"],
    "<operator>_+": "+",
    "<operator>_-": "-",
    "<operator>_*": "*",
    "<operator>_/": "/",
    "<operator>_%": "%",
    "<operator>_**": "**",
    "<operator>_//": "//",
    "<tint>_tint literal": "tint literal",
    "<tint>_lent": "lent",
    "<tint>_tint": "tint",
    "<tint>_#": "#",
    "<flora>_flora literal": "flora literal",
    "<flora>_flora": "flora",
    "<flora>_#": "#",
    "<concatenate>_<indexing>": ["[", "EPSILON"],
    "<concatenate>_EPSILON": [
        "+",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "EPSILON",
        ",",
        ";",
        ")",
    ],
    "<condition>_<data>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
    ],
    "<condition>_<sequence>": [
        "string literal",
        "[",
        "{",
        "getItems",
        "getKeys",
        "getValues",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
    ],
    "<operate-logic>_<cond-operator>": [
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
    ],
    "<operate-logic>_EPSILON": [
        "(",
        "EPSILON",
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<cond-operator>_==": "==",
    "<cond-operator>_!=": "!=",
    "<cond-operator>_>": ">",
    "<cond-operator>_<": "<",
    "<cond-operator>_>=": ">=",
    "<cond-operator>_<=": "<=",
    "<cond-operator>_=&": "=&",
    "<cond-operator>_=/": "=/",
    "<cond-operator>_at": "at",
    "<cond-operator>_nut": "nut",
    "<nuts-and-ats>_at": "at",
    "<nuts-and-ats>_nut": "nut",
    "<nuts-and-ats>_EPSILON": [
        "(",
        "EPSILON",
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<supply-dirt>_getItems": "getItems",
    "<supply-dirt>_getKeys": "getKeys",
    "<supply-dirt>_getValues": "getValues",
    "<insert-func>_(": "(",
    "<insert-func>_EPSILON": [
        "[",
        "EPSILON",
        ",",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "+",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        ",",
        ";",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
    ],
    "<instance-grab>_.": ".",
    "<instance-grab>_EPSILON": [
        "[",
        "EPSILON",
        ",",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "+",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        ",",
        ";",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
    ],
    "<indexing>_[": "[",
    "<indexing>_EPSILON": [
        "[",
        "EPSILON",
        ",",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "+",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        ",",
        ";",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
    ],
    "<typecast>_(": "(",
    "<typecast>_EPSILON": [
        ",",
        "EPSILON",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
    ],
    "<more-data>_,": ",",
    "<more-data>_EPSILON": ";",
    "<sqnc-type>_florist": "florist",
    "<sqnc-type>_tulip": "tulip",
    "<sqnc-type>_dirt": "dirt",
    "<sqnc-type>_stem": "stem",
    "<sqnc-value>_=": "=",
    "<sqnc-value>_EPSILON": [",", "EPSILON", ";", ")"],
    "<sequence>_<dirt>": ["string literal", "EPSILON"],
    "<sequence>_<supply-dirt>": ["getItems", "getKeys", "getValues"],
    "<sequence>_<sqnc-type>": ["florist", "tulip", "dirt", "stem"],
    "<sequence>_#": "#",
    "<open>_[": "[",
    "<open>_{": "{",
    "<dirt>_string literal": "string literal",
    "<dirt>_EPSILON": [
        "[",
        "{",
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "]",
        "}",
    ],
    "<close>_]": "]",
    "<close>_}": "}",
    "<more-sqnc>_,": ",",
    "<more-sqnc>_EPSILON": ";",
    "<insert-sqnc>_<data>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
    ],
    "<insert-sqnc>_<open>": ["[", "{"],
    "<insert-sqnc>_*": "*",
    "<insert-sqnc>_EPSILON": ["]", "}"],
    "<next-sqnc>_,": ",",
    "<next-sqnc>_EPSILON": ["]", "}"],
    "<insert-next-sqnc>_<dirt>": ["string literal", "EPSILON"],
    "<insert-next-sqnc>_*": "*",
    "<start-end-step>_[": "[",
    "<start-end-step>_EPSILON": [
        ",",
        "EPSILON",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
    ],
    "<insert-start>_<insert-data>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "(",
    ],
    "<insert-start>_:": ":",
    "<close-start>_<close-end>": ["]", ":"],
    "<close-start>_<insert-data>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "(",
    ],
    "<close-end>_]": "]",
    "<close-end>_:": ":",
    "<skip-start>_<insert-data>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "(",
    ],
    "<skip-start>_:": ":",
    "<all-type-value>_<insert-data>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "(",
    ],
    "<all-type-value>_<sequence>": [
        "string literal",
        "[",
        "{",
        "getItems",
        "getKeys",
        "getValues",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
    ],
    "<all-type-value>_inpetal": "inpetal",
    "<i/o-statement>_<insert-inpetal>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
    ],
    "<i/o-statement>_mint": "mint",
    "<insert-inpetal>_<common-type>": ["tint", "flora", "chard", "string", "bloom"],
    "<insert-inpetal>_<sqnc-type>": ["florist", "tulip", "dirt", "stem"],
    "<insert-inpetal>_#": "#",
    "<more-id>_,": ",",
    "<more-id>_EPSILON": ["=", "+=", "-=", "*=", "/=", "%=", "**=", "//="],
    "<eleaf>_eleaf": "eleaf",
    "<eleaf>_EPSILON": [
        "moss",
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "mint",
        "leaf",
        "fern",
        "willow",
        "tree",
        "clear",
        "break",
        "EPSILON",
        ")",
        "regrow",
    ],
    "<else>_moss": "moss",
    "<else>_EPSILON": [
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "mint",
        "leaf",
        "fern",
        "willow",
        "tree",
        "clear",
        "break",
        "EPSILON",
        ")",
        "regrow",
    ],
    "<assignment>_<insert-inpetal>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
    ],
    "<assignment>_<assign>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "EPSILON",
    ],
    "<assign>_<insert-inpetal>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
    ],
    "<assign>_EPSILON": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<insert-assign>_<common-type>": ["tint", "flora", "chard", "string", "bloom"],
    "<insert-assign>_<sqnc-type>": ["florist", "tulip", "dirt", "stem"],
    "<assignment-op>_=": "=",
    "<assignment-op>_+=": "+=",
    "<assignment-op>_-=": "-=",
    "<assignment-op>_*=": "*=",
    "<assignment-op>_/=": "/=",
    "<assignment-op>_%=": "%=",
    "<assignment-op>_**=": "**=",
    "<assignment-op>_//=": "//=",
    "<iterative>_fern": "fern",
    "<iterative>_willow": "willow",
    "<insert-fern>_tint": "tint",
    "<insert-fern>_<all-type-value>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
    ],
    "<more-value>_,": ",",
    "<more-value>_EPSILON": "at",
    "<check-branch>_<all-type-value>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
    ],
    "<check-branch>__:": "_:",
    "<insert-branch>_:": ":",
    "<insert-branch>_leaf": "leaf",
    "<operate-branch>_<statement>": [
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "mint",
        "leaf",
        "fern",
        "willow",
        "tree",
        "clear",
        "break",
        "EPSILON",
    ],
    "<operate-branch>_branch": "branch",
    "<more-branch>_branch": "branch",
    "<more-branch>_EPSILON": ")",
    "<argument>_<insert-argument>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
        "EPSILON",
    ],
    "<argument>_<common-type>": ["tint", "flora", "chard", "string", "bloom"],
    "<argument>_EPSILON": ")",
    "<insert-argument>_<all-type-value>": [
        "tint literal",
        "flora literal",
        "chard literal",
        "string literal",
        "bloom literal",
        "#",
        "lent",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "getItems",
        "getKeys",
        "getValues",
        "bare",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
    ],
    "<insert-argument>_#": "#",
    "<insert-argument>_EPSILON": ")",
    "<add-argument>_,": ",",
    "<add-argument>_EPSILON": ")",
    "<more**kwargs>_,": ",",
    "<more**kwargs>_EPSILON": ")",
    "<function>_<common-type>": ["tint", "flora", "chard", "string", "bloom"],
    "<function>_viola": "viola",
    "<function>_EPSILON": "plant",
    "<add-at>_<more-value>": [",", "EPSILON"],
    "<add-at>_EPSILON": ";",
    "<parameter>_<undefined-param>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "**",
        "EPSILON",
    ],
    "<parameter>_<common-type>": ["tint", "flora", "chard", "string", "bloom"],
    "<parameter>_<sqnc-type>": ["florist", "tulip", "dirt", "stem"],
    "<parameter>_#": "#",
    "<parameter>_EPSILON": ")",
    "<undefined-param>_<common-type>": ["tint", "flora", "chard", "string", "bloom"],
    "<undefined-param>_**": "**",
    "<undefined-param>_EPSILON": ")",
    "<add-kwargs>_,": ",",
    "<add-kwargs_EPSILON": ")",
    "<next-parameter>_,": ",",
    "<next-parameter>_EPSILON": ")",
}
