""" This Module Contains the Syntax of C-Grass Plus """

FIRST_SET = {
    "<program>": "seed",
    "<global>": ["floral", "EPSILON"],
    "<constant>": ["hard", "EPSILON"],
    "<statement>": [
        "tree",
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
        "EPSILON",
    ],
    "<filter-statement>": [
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
        "EPSILON",
    ],
    "<insert-variable>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<sqnc-type>": ["florist", "tulip", "dirt", "stem"],
    "<tint-value>": ["=", "EPSILON"],
    "<tint>": [
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
        "tint",
        "(",
    ],
    "<tint-literals>": [
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
    ],
    "<flora-value>": ["=", "EPSILON"],
    "<flora>": [
        "Flora Literal",
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
        "flora",
        "(",
    ],
    "<arithmetic>": [
        "Flora Literal",
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
        "flora",
        "(",
    ],
    "<flora-literals>": [
        "Flora Literal",
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
    ],
    "<operate-number>": ["+", "-", "*", "/", "%", "**", "//", "EPSILON"],
    "<operator>": ["+", "-", "*", "/", "%", "**", "//"],
    "<chard-value>": ["=", "EPSILON"],
    "<chard>": ["Chard Literal", "#", "getItems", "getKeys", "getValues", "chard"],
    "<chard-literals>": ["Chard Literal", "#", "getItems", "getKeys", "getValues"],
    "<string-value>": ["=", "EPSILON"],
    "<string>": ["String Literal", "#", "getItems", "getKeys", "getValues", "string"],
    "<string-literals>": ["String Literal", "#", "getItems", "getKeys", "getValues"],
    "<concatenate>": ["[", "+", "EPSILON"],
    "<bloom-value>": ["=", "EPSILON"],
    "<insert-condition>": [
        "bloom literal",
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
        "tint",
        "Flora Literal",
        "flora",
        "Chard Literal",
        "chard",
        "String Literal",
        "string",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "bare",
        "(",
        "bloom",
    ],
    "<bloom>": [
        "bloom literal",
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
        "tint",
        "Flora Literal",
        "flora",
        "Chard Literal",
        "chard",
        "String Literal",
        "string",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "bare",
        "(",
        "bloom",
    ],
    "<sqnc-bloom>": [
        "[",
        "{",
        "getItems",
        "getKeys",
        "getValues",
        "#",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "(",
    ],
    "<bloom-literals>": [
        "bloom literal",
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
        "tint",
        "Flora Literal",
        "flora",
        "Chard Literal",
        "chard",
        "String Literal",
        "string",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "bare",
    ],
    "<operate-logic>": [
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "EPSILON",
    ],
    "<cond-operator>": ["==", "!=", ">", "<", ">=", "<=", "=&", "=/", "at", "nut"],
    "<insert-func>": ["(", "EPSILON"],
    "<instance-grab>": [".", "EPSILON"],
    "<indexing>": ["[", "EPSILON"],
    "<insert-index>": ["Tint Literal", "String Literal"],
    "<more-tint>": [",", "EPSILON"],
    "<more-flora>": [",", "EPSILON"],
    "<more-chard>": [",", "EPSILON"],
    "<more-string>": [",", "EPSILON"],
    "<more-bloom>": [",", "EPSILON"],
    "<sqnc-value>": ["=", "EPSILON"],
    "<more-sqnc>": [",", "EPSILON"],
    "<more-id>": [",", "EPSILON"],
    "<sqnc>": [
        "[",
        "{",
        "getItems",
        "getKeys",
        "getValues",
        "#",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<sqnc-literals>": ["[", "{", "getItems", "getKeys", "getValues", "#"],
    "<supply-dirt>": ["getItems", "getKeys", "getValues"],
    "<open>": ["[", "{"],
    "<dirt>": ["String Literal", "EPSILON"],
    "<close>": ["]", "}"],
    "<sequence>": [
        "String Literal",
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
        "tint",
        "Flora Literal",
        "flora",
        "(",
        "Chard Literal",
        "chard",
        "string",
        "bloom literal",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "bare",
        "bloom",
    ],
    "<common-data>": [
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
        "tint",
        "Flora Literal",
        "flora",
        "(",
        "Chard Literal",
        "chard",
        "String Literal",
        "string",
        "bloom literal",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "bare",
        "bloom",
    ],
    "<next-sqnc>": [",", "EPSILON"],
    "<2D-sqnc>": [
        "String Literal",
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
        "tint",
        "Flora Literal",
        "flora",
        "(",
        "Chard Literal",
        "chard",
        "string",
        "bloom literal",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "bare",
        "bloom",
    ],
    "<next-2D-sqnc>": [",", "EPSILON"],
    "<next-3D-sqnc>": [",", "EPSILON"],
    "<start-end-step>": ["[", "EPSILON"],
    "<insert-start>": ["Tint Literal", ":"],
    "<close-start>": ["]", ":", "Tint Literal"],
    "<close-end>": ["]", ":"],
    "<skip-start>": ["Tint Literal", ":"],
    "<2D-start-end-step>": ["[", "EPSILON"],
    "<2D-insert-start>": ["Tint Literal", ":"],
    "<2D-close-start>": ["]", ":", "Tint Literal"],
    "<2D-close-end>": ["]", ":"],
    "<2D-skip-start>": ["Tint Literal", ":"],
    "<3D-start-end-step>": ["[", "EPSILON"],
    "<3D-insert-start>": ["Tint Literal", ":"],
    "<3D-close-start>": ["]", ":", "Tint Literal"],
    "<3D-close-end>": ["]", ":"],
    "<3D-skip-start>": ["Tint Literal", ":"],
    "<all-type-value>": [
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
        "tint",
        "Flora Literal",
        "flora",
        "(",
        "Chard Literal",
        "chard",
        "String Literal",
        "string",
        "bloom literal",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "bare",
        "bloom",
        "inpetal",
    ],
    "<i/o-statement>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "mint",
    ],
    "<insert-inpetal>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
    ],
    "<common-type>": ["tint", "flora", "chard", "string", "bloom"],
    "<eleaf>": ["eleaf", "EPSILON"],
    "<2D-eleaf>": ["eleaf", "EPSILON"],
    "<3D-eleaf>": ["eleaf", "EPSILON"],
    "<final-eleaf>": ["eleaf", "EPSILON"],
    "<else>": ["moss", "EPSILON"],
    "<2D-else>": ["moss", "EPSILON"],
    "<3D-else>": ["moss", "EPSILON"],
    "<final-else>": ["moss", "EPSILON"],
    "<iterative>": ["fern", "willow"],
    "<insert-fern>": [
        "tint",
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
        "Flora Literal",
        "flora",
        "(",
        "Chard Literal",
        "chard",
        "String Literal",
        "string",
        "bloom literal",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "bare",
        "bloom",
        "inpetal",
    ],
    "<assignment>": [
        "#",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<assign>": ["=", "+=", "-=", "*=", "/=", "%=", "**=", "//=", "EPSILON"],
    "<assignment-op>": ["=", "+=", "-=", "*=", "/=", "%=", "**=", "//="],
    "<more-value>": [",", "EPSILON"],
    "<final-value>": [",", "EPSILON"],
    "<use-tree>": ["tree", "EPSILON"],
    "<check-branch>": [
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
        "tint",
        "Flora Literal",
        "flora",
        "(",
        "Chard Literal",
        "chard",
        "String Literal",
        "string",
        "bloom literal",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "bare",
        "bloom",
        "inpetal",
        "_:",
    ],
    "<insert-branch>": [":", "leaf"],
    "<more-branch>": ["branch", "EPSILON"],
    "<2D-statement>": [
        "tree",
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
        "EPSILON",
    ],
    "<use-2D-tree>": ["tree", "EPSILON"],
    "<check-2D-branch>": [
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
        "tint",
        "Flora Literal",
        "flora",
        "(",
        "Chard Literal",
        "chard",
        "String Literal",
        "string",
        "bloom literal",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "bare",
        "bloom",
        "inpetal",
        "_:",
    ],
    "<insert-2D-branch>": [":", "leaf"],
    "<more-2D-branch>": ["branch", "EPSILON"],
    "<filter-2D-state>": [
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
        "EPSILON",
    ],
    "<2D-iterative>": ["fern", "willow"],
    "<insert-2D-fern>": [
        "tint",
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
        "Flora Literal",
        "flora",
        "(",
        "Chard Literal",
        "chard",
        "String Literal",
        "string",
        "bloom literal",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "bare",
        "bloom",
        "inpetal",
    ],
    "<3D-statement>": [
        "tree",
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
        "EPSILON",
    ],
    "<use-3D-tree>": ["tree", "EPSILON"],
    "<check-3D-branch>": [
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
        "tint",
        "Flora Literal",
        "flora",
        "(",
        "Chard Literal",
        "chard",
        "String Literal",
        "string",
        "bloom literal",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "bare",
        "bloom",
        "inpetal",
        "_:",
    ],
    "<insert-3D-branch>": [":", "leaf"],
    "<more-3D-branch>": ["branch", "EPSILON"],
    "<filter-3D-state>": [
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
        "EPSILON",
    ],
    "<3D-iterative>": ["fern", "willow"],
    "<insert-3D-fern>": [
        "tint",
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
        "Flora Literal",
        "flora",
        "(",
        "Chard Literal",
        "chard",
        "String Literal",
        "string",
        "bloom literal",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "bare",
        "bloom",
        "inpetal",
    ],
    "<final-statement>": [
        "tree",
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
        "EPSILON",
    ],
    "<use-final-tree>": ["tree", "EPSILON"],
    "<check-final-branch>": [
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
        "tint",
        "Flora Literal",
        "flora",
        "(",
        "Chard Literal",
        "chard",
        "String Literal",
        "string",
        "bloom literal",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "bare",
        "bloom",
        "inpetal",
        "_:",
    ],
    "<insert-final-branch>": [":", "leaf"],
    "<more-final-branch>": ["branch", "EPSILON"],
    "<filter-final-state>": [
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
        "EPSILON",
    ],
    "<argument>": [
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
        "tint",
        "Flora Literal",
        "flora",
        "(",
        "Chard Literal",
        "chard",
        "String Literal",
        "string",
        "bloom literal",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "bare",
        "bloom",
        "inpetal",
        "EPSILON",
    ],
    "<insert-argument>": [
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
        "tint",
        "Flora Literal",
        "flora",
        "(",
        "Chard Literal",
        "chard",
        "String Literal",
        "string",
        "bloom literal",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "bare",
        "bloom",
        "inpetal",
        "EPSILON",
    ],
    "<insert**kwargs>": ["tint", "flora", "chard", "string", "bloom"],
    "<more**kwargs>": [",", "EPSILON"],
    "<add-argument>": [",", "EPSILON"],
    "<2D-argument>": [
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
        "tint",
        "Flora Literal",
        "flora",
        "(",
        "Chard Literal",
        "chard",
        "String Literal",
        "string",
        "bloom literal",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "bare",
        "bloom",
        "inpetal",
    ],
    "<add-2D-argument>": [",", "EPSILON"],
    "<add-3D-argument>": [",", "EPSILON"],
    "<function>": ["tint", "flora", "chard", "string", "bloom", "viola", "EPSILON"],
    "<add-at>": [",", "at", "EPSILON"],
    "<common-variable>": ["tint", "flora", "chard", "string", "bloom"],
    "<parameter>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "**",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "EPSILON",
    ],
    "<undefined-param>": ["tint", "flora", "chard", "string", "bloom", "**", "EPSILON"],
    "<add-kwargs>": [",", "EPSILON"],
    "<next-parameter>": [",", "EPSILON"],
    "<2D-parameter>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "**",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "EPSILON",
    ],
    "<next-2D-param>": [",", "EPSILON"],
    "<3D-parameter>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "**",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "EPSILON",
    ],
    "<next-3D-param>": [",", "EPSILON"],
}

FOLLOW_SET = {
    "<program>": "EPSILON",
    "<global>": "garden",
    "<constant>": [
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<statement>": [")", "regrow"],
    "<filter-statement>": [
        "tree",
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
        "EPSILON",
        ")",
        "regrow",
        "branch",
    ],
    "<insert-variable>": ";",
    "<sqnc-type>": ["#", "("],
    "<tint-value>": [",", "EPSILON", ";", ")"],
    "<tint>": [
        ",",
        "EPSILON",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "{",
        ":",
        "leaf",
        "]",
        "}",
    ],
    "<tint-literals>": [
        ",",
        "EPSILON",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "(",
        ":",
        "leaf",
        "]",
        "}",
        "+",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
    ],
    "<flora-value>": [",", "EPSILON", ";", ")"],
    "<flora>": [
        ",",
        "EPSILON",
        ";",
        ")",
        "+",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        "]" "}",
        ")",
        "at",
        ":",
        "leaf",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "nut",
        "(",
    ],
    "<arithmetic>": [
        ",",
        "EPSILON",
        ";",
        ")",
        "+",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        "]" "}",
        ")",
        "at",
        ":",
        "leaf",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "nut",
        "(",
    ],
    "<flora-literals>": [
        ",",
        "EPSILON",
        ";",
        ")",
        "+",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        "]" "}",
        ")",
        "at",
        ":",
        "leaf",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "nut",
        "(",
    ],
    "<operate-number>": [
        ",",
        "EPSILON",
        ";",
        ")",
        "+",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        "]" "}",
        ")",
        "at",
        ":",
        "leaf",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "nut",
        "(",
    ],
    "<operator>": [
        "Flora Literal",
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
        "flora",
        "(",
    ],
    "<chard-value>": [",", "EPSILON", ";", ")"],
    "<chard>": [
        ",",
        "EPSILON",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "(",
        ":",
        "leaf",
        "]",
        "}",
    ],
    "<chard-literals>": [
        ",",
        "EPSILON",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "(",
        ":",
        "leaf",
        "]",
        "}",
    ],
    "<string-value>": [",", "EPSILON", ";", ")"],
    "<string>": [
        ",",
        "EPSILON",
        ";",
        ")",
        "[",
        "+",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "(",
        ":",
        "leaf",
        "]",
        "}",
    ],
    "<string-literals>": [
        "[",
        "+",
        "EPSILON",
        ",",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "(",
        ":",
        "leaf",
        "]",
        "}",
    ],
    "<concatenate>": [
        ",",
        "EPSILON",
        ";",
        ")",
        "[",
        "+",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "(",
        ":",
        "leaf",
        "]",
        "}",
    ],
    "<bloom-value>": [",", "EPSILON", ";", ")"],
    "<insert-condition>": [")", "{", "EPSILON", ";", ",", "at", ":", "leaf", "]", "}"],
    "<bloom>": [")", ";", "(", ",", "EPSILON", "]", "}", "at", ":", "leaf"],
    "<sqnc-bloom>": [")", "(", "EPSILON", ";", ",", "at", ":", "leaf", "]", "}"],
    "<bloom-literals>": [
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "EPSILON",
        ")",
        "(",
        ";",
        ",",
        ":",
        "leaf",
        "]",
        "}",
    ],
    "<operate-logic>": [")", ";", "(", ",", "EPSILON", "]", "}", "at", ":", "leaf"],
    "<cond-operator>": [
        "bloom literal",
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
        "tint",
        "Flora Literal",
        "flora",
        "Chard Literal",
        "chard",
        "String Literal",
        "string",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "bare",
        "(",
        "bloom",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
    ],
    "<insert-func>": [
        "[",
        "EPSILON",
        ")",
        ",",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
        ";",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "+",
        "(",
        ":",
        "leaf",
        "]",
        "}",
        "(",
        ";",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
    ],
    "<instance-grab>": [
        "[",
        "EPSILON",
        ")",
        ",",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
        ";",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "+",
        "(",
        ":",
        "leaf",
        "]",
        "}",
        "(",
        ";",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
    ],
    "<indexing>": [
        ",",
        "EPSILON",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "(",
        ":",
        "leaf",
        "]",
        "}",
        "+",
        "-",
        "*",
        "/",
        "%",
        "**",
        "//",
        "[",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
    ],
    "<insert-index>": "]",
    "<more-tint>": ";",
    "<more-flora>": ";",
    "<more-chard>": ";",
    "<more-string>": ";",
    "<more-bloom>": ";",
    "<sqnc-value>": [",", "EPSILON", ";", ")"],
    "<more-sqnc>": ";",
    "<more-id>": [
        ")",
        ",",
        "at",
        ";",
        "EPSILON",
        ":",
        "leaf",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
    ],
    "<sqnc>": [
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "EPSILON",
        ")",
        "[",
        "+",
        ";",
        "{",
        ",",
        ":",
        "leaf",
        "]",
        "}",
        "(",
    ],
    "<supply-dirt>": "(",
    "<open>": [
        "String Literal",
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
        "tint",
        "Flora Literal",
        "flora",
        "(",
        "Chard Literal",
        "chard",
        "string",
        "bloom literal",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "bare",
        "bloom",
    ],
    "<dirt>": [
        "Tint Literal",
        "#",
        "lent",
        "getItems",
        "getKeys",
        "getValues",
        "tint",
        "Flora Literal",
        "flora",
        "(",
        "Chard Literal",
        "chard",
        "String Literal",
        "string",
        "bloom literal",
        "[",
        "{",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "bare",
        "bloom",
    ],
    "<close>": [
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "EPSILON",
        ")",
        "[",
        "+",
        ";",
        "{",
        ",",
        ":",
        "leaf",
        "]",
        "}",
        "(",
    ],
    "<sequence>": ["]", "}"],
    "<common-data>": [",", "EPSILON", "]", "}", ";", ")", "at", ":", "leaf"],
    "<next-sqnc>": ["]", "}"],
    "<2D-sqnc>": ["]", "}"],
    "<next-2D-sqnc>": ["]", "}"],
    "<next-3D-sqnc>": ["]", "}"],
    "<start-end-step>": [
        "[",
        "+",
        "EPSILON",
        ",",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "(",
        ":",
        "leaf",
        "]",
        "}",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
        "+",
    ],
    "<insert-start>": [
        "[",
        "+",
        "EPSILON",
        ",",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "(",
        ":",
        "leaf",
        "]",
        "}",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
        "+",
    ],
    "<close-start>": [
        "[",
        "+",
        "EPSILON",
        ",",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "(",
        ":",
        "leaf",
        "]",
        "}",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
        "+",
    ],
    "<close-end>": [
        "[",
        "+",
        "EPSILON",
        ",",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "(",
        ":",
        "leaf",
        "]",
        "}",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
        "+",
    ],
    "<skip-start>": [
        "[",
        "+",
        "EPSILON",
        ",",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "(",
        ":",
        "leaf",
        "]",
        "}",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
        "+",
    ],
    "<2D-start-end-step>": [
        "[",
        "+",
        "EPSILON",
        ",",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "(",
        ":",
        "leaf",
        "]",
        "}",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
        "+",
    ],
    "<2D-insert-start>": [
        "[",
        "+",
        "EPSILON",
        ",",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "(",
        ":",
        "leaf",
        "]",
        "}",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
        "+",
    ],
    "<2D-close-start>": [
        "[",
        "+",
        "EPSILON",
        ",",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "(",
        ":",
        "leaf",
        "]",
        "}",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
        "+",
    ],
    "<2D-close-end>": [
        "[",
        "+",
        "EPSILON",
        ",",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "(",
        ":",
        "leaf",
        "]",
        "}",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
        "+",
    ],
    "<2D-skip-start>": [
        "[",
        "+",
        "EPSILON",
        ",",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "(",
        ":",
        "leaf",
        "]",
        "}",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
        "+",
    ],
    "<3D-start-end-step>": [
        "[",
        "+",
        "EPSILON",
        ",",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "(",
        ":",
        "leaf",
        "]",
        "}",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
        "+",
    ],
    "<3D-insert-start>": [
        "[",
        "+",
        "EPSILON",
        ",",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "(",
        ":",
        "leaf",
        "]",
        "}",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
        "+",
    ],
    "<3D-close-start>": [
        "[",
        "+",
        "EPSILON",
        ",",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "(",
        ":",
        "leaf",
        "]",
        "}",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
        "+",
    ],
    "<3D-close-end>": [
        "[",
        "+",
        "EPSILON",
        ",",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "(",
        ":",
        "leaf",
        "]",
        "}",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
        "+",
    ],
    "<3D-skip-start>": [
        "[",
        "+",
        "EPSILON",
        ",",
        ";",
        ")",
        "==",
        "!=",
        ">",
        "<",
        ">=",
        "<=",
        "=&",
        "=/",
        "at",
        "nut",
        "(",
        ":",
        "leaf",
        "]",
        "}",
        "=",
        "+=",
        "-=",
        "*=",
        "/=",
        "%=",
        "**=",
        "//=",
        "+",
    ],
    "<all-type-value>": [";", ")", ",", "at", "EPSILON", ":", "leaf"],
    "<i/o-statement>": ";",
    "<insert-inpetal>": "inpetal",
    "<common-type>": ["#", "*"],
    "<eleaf>": [
        "moss",
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
        "EPSILON",
        "tree",
        ")",
        "regrow",
        "branch",
    ],
    "<2D-eleaf>": [
        "moss",
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
        "EPSILON",
        "tree",
        ")",
        "branch",
    ],
    "<3D-eleaf>": [
        "moss",
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
        "EPSILON",
        "tree",
        ")",
        "branch",
    ],
    "<final-eleaf>": [
        "moss",
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
        "EPSILON",
        "tree",
        ")",
        "branch",
    ],
    "<else>": [
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
        "EPSILON",
        "tree",
        ")",
        "regrow",
        "branch",
    ],
    "<2D-else>": [
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
        "EPSILON",
        "tree",
        ")",
        "branch",
    ],
    "<3D-else>": [
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
        "EPSILON",
        "tree",
        ")",
        "branch",
    ],
    "<final-else>": [
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
        "EPSILON",
        "tree",
        ")",
        "branch",
    ],
    "<iterative>": ";",
    "<insert-fern>": ";",
    "<assignment>": ";",
    "<assign>": ";",
    "<assignment-op>": [
        "Tint Literal",
        "#",
        "lent",
        "tint",
        "Flora Literal",
        "flora",
        "(",
        "Chard Literal",
        "chard",
        "String Literal",
        "string",
        "bloom literal",
        "bloom",
        "bare",
        "[",
        "{",
        "getItems",
        "getKeys",
        "getValues",
        "#",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "inpetal",
    ],
    "<more-value>": "at",
    "<final-value>": "at",
    "<use-tree>": [
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
        "tree",
        "EPSILON",
        ")",
        "regrow",
    ],
    "<check-branch>": ")",
    "<insert-branch>": ["branch", "EPSILON", ")"],
    "<more-branch>": ")",
    "<2D-statement>": ")",
    "<use-2D-tree>": [
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
        "tree",
        "EPSILON",
        ")",
    ],
    "<check-2D-branch>": ")",
    "<insert-2D-branch>": ["branch", "EPSILON", ")"],
    "<more-2D-branch>": ")",
    "<filter-2D-state>": [
        ")",
        "tree",
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
        "EPSILON",
        "branch",
    ],
    "<2D-iterative>": ";",
    "<insert-2D-fern>": ";",
    "<3D-statement>": ")",
    "<use-3D-tree>": [
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
        "tree",
        "EPSILON",
        ")",
    ],
    "<check-3D-branch>": ")",
    "<insert-3D-branch>": ["branch", "EPSILON", ")"],
    "<more-3D-branch>": ")",
    "<filter-3D-state>": [
        ")",
        "tree",
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
        "EPSILON",
        "branch",
    ],
    "<3D-iterative>": ";",
    "<insert-3D-fern>": ";",
    "<final-statement>": ")",
    "<use-final-tree>": [
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
        "tree",
        "EPSILON",
        ")",
    ],
    "<check-final-tree>": ")",
    "<insert-final-branch>": ["branch", "EPSILON", ")"],
    "<more-final-branch>": ")",
    "<filter-final-state>": [
        ")",
        "tree",
        "hard",
        "tint",
        "flora",
        "chard",
        "string",
        "bloom",
        "florist",
        "tulip",
        "dirt",
        "stem",
        "#",
        "inpetal",
        "mint",
        "leaf",
        "fern",
        "willow",
        "clear",
        "break",
        "EPSILON",
        "branch",
    ],
    "<argument>": ")",
    "<insert-argument>": ")",
    "<insert**kwargs>": [",", "EPSILON", ")"],
    "<more**kwargs>": [",", "EPSILON", ")"],
    "<add-argument>": ")",
    "<2D-argument>": ")",
    "<add-3D-argument>": ")",
    "<add-3D-argument>": ")",
    "<function>": "plant",
    "<add-at>": ";",
    "<common-variable>": [",", "EPSILON", ")"],
    "<parameter>": ")",
    "<undefined-param>": ")",
    "<add-kwargs>": ")",
    "<next-parameter>": ")",
    "<2D-parameter>": ")",
    "<next-2D-param>": ")",
    "<3D-parameter>": ")",
    "<next-3D-param>": ")",
}
